# Generated by Django 4.2.9 on 2024-01-16 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrexApp', '0002_schoolform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolform',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='schoolform',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='schoolform',
            name='sex',
        ),
        migrations.AddField(
            model_name='schoolform',
            name='purpose',
            field=models.TextField(blank=True, max_length=150, verbose_name='Purpose of Request'),
        ),
        migrations.AddField(
            model_name='schoolform',
            name='request_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Request Date'),
        ),
        migrations.AddField(
            model_name='schoolform',
            name='requestform',
            field=models.CharField(blank=True, choices=[('', 'Choose User Type'), ('student', 'Student'), ('parent', 'Parent')], max_length=10, verbose_name='Forms'),
        ),
        migrations.AddField(
            model_name='schoolform',
            name='specialinstructions',
            field=models.TextField(blank=True, max_length=150, verbose_name='Special Instructions'),
        ),
        migrations.AlterField(
            model_name='schoolform',
            name='user_type',
            field=models.CharField(blank=True, choices=[('', 'Choose User Type'), ('student', 'Student'), ('parent', 'Parent')], max_length=10, verbose_name='Role'),
        ),
    ]
