# Generated by Django 4.2.9 on 2024-01-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrexApp', '0003_remove_schoolform_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolform',
            name='requestform',
            field=models.CharField(blank=True, choices=[('', 'What are you requesting?'), ('f137', 'F137'), ('coe', 'COE')], max_length=10, verbose_name='Forms'),
        ),
    ]
