# Generated by Django 4.2.9 on 2024-01-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrexApp', '0004_alter_schoolform_requestform'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolform',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=10, verbose_name='status'),
        ),
    ]
