# Generated by Django 4.2.9 on 2024-01-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrexApp', '0005_schoolform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolform',
            name='date_released',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date released'),
        ),
    ]
