# Generated by Django 4.2.9 on 2024-01-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vrexApp', '0009_schoolform_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolform',
            name='user',
        ),
    ]
